{% set python_min = "3.10" %}
{% set name = "txl-editors" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_editors-{{ version }}.tar.gz
  sha256: 4d3dee5e15e700b05a9199fb81e81ef5d452c0b368321af03f03626a49f7c9b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_editors

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/editors
  summary: TXL plugin for editors
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/editors
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
