{% set python_min = "3.10" %}
{% set name = "txl-editors" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_editors-{{ version }}.tar.gz
  sha256: 8cfea72fd159cb4bae1af1d58aae3d945c5838057c32840628886e82296a769b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_editors

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/editors
  summary: TXL plugin for editors
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/editors
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
